name = "UnitfulGaussian"
uuid = "203183ea-d3ea-452b-8588-590cbae10604"
authors = ["Abhro R. and contributors"]
version = "0.1.1"

[deps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulEquivalences = "da9c4bc3-91c8-4f02-8a40-6b990d2a7e0c"

[compat]
Unitful = "1.23"
UnitfulEquivalences = "0.2"
julia = "1.10"
